services:
        nelmio_api_doc.form.extension.description_form_type_extension:
            class: Nelmio\ApiDocBundle\Form\Extension\DescriptionFormTypeExtension
        tags:
            - { name: form.type_extension , alias: form}