services:
    nelmio_api_doc.extractor.api_doc_extractor:
        class: Eliberty\ApiBundle\Nelmio\Extractor\ApiDocExtractor
        arguments:
            - '@service_container'
            - '@router'
            - '@annotation_reader'
            - '@nelmio_api_doc.doc_comment_extractor'
            - '@nelmio_api_doc.controller_name_parser'
            - []
            - []
            - '@api.transformer.helper'
            - '@api.normalizer.item'
            - '@api.resource_collection'
            - '@doctrine.orm.entity_manager'
            - '@form.registry'

    eliberty_api_doc.formatter.file_formatter:
        class: Eliberty\ApiBundle\Nelmio\Formatter\MkDocsFormatter
        arguments:
            - '%kernel.root_dir%'
            - '@templating'
            - '@api.normalizer.item'
            - '@api.resource_collection'
            - '@doctrine'
            - '@property_accessor'
            - '@api.data_provider'