parameters:
    eliberty_api.normalizer.item.class: Eliberty\ApiBundle\JsonLd\Serializer\Normalizer

services:
        api.resource:
            class: Eliberty\ApiBundle\Api\Resource
            abstract: true

        api.json_ld.entrypoint_builder:
            class: Eliberty\ApiBundle\JsonLd\EntrypointBuilder
            arguments:
                 - @api.resource_collection
                 - @api.iri_converter
                 - @api.router

        api.doctrine.orm.data_provider:
            class: Eliberty\ApiBundle\Doctrine\Orm\DataProvider
            arguments:
                 - @doctrine
                 - %api.collection.order%
                 - %api.collection.pagination.page_parameter_name%
                 - %api.collection.pagination.items_per_page.number%
                 - %api.collection.pagination.items_per_page.enable_client_request%
                 - %api.collection.pagination.items_per_page.parameter_name%
            tags:
                 - { name: api.data_provider }

        eliberty.api.hydra.normalizer.violation.list.error:
            class: Eliberty\ApiBundle\Hydra\Serializer\ErrorViolationListNormalizer
            arguments:
                 - @api.router
                 - %kernel.debug%
                 - @property_accessor
            tags:
                 - { name: serializer.normalizer }

        api.json_ld.normalizer.item:
            class: %eliberty_api.normalizer.item.class%
            arguments:
                - @api.resource_collection
                - @api.data_provider
                - @api.router
                - @api.mapping.class_metadata_factory
                - @api.json_ld.context_builder
                - @property_accessor
                - @api.transformer.helper
                - @request_stack
                - @doctrine.orm.entity_manager
                - @logger
            tags:
                - { name: serializer.normalizer }

        api.ressource.transformer_resolver:
            class: Eliberty\ApiBundle\Transformer\Listener\TransformerResolver
            arguments:
                - @request_stack

        api.resource_collection:
            class: Eliberty\ApiBundle\Api\ResourceCollection
            arguments:
                - @request_stack
            lazy: true

        api.operation_factory:
            class: Eliberty\ApiBundle\Api\Operation\OperationFactory
            arguments:
                - @api.transformer.helper

        api.router:
            class: Eliberty\ApiBundle\Routing\Router
            arguments:
                - @router
                - @api.resource_collection
                - @property_accessor

        api.json_ld.context_builder:
            class: Eliberty\ApiBundle\JsonLd\ContextBuilder
            arguments:
                - @api.router
                - @api.mapping.class_metadata_factory
                - @api.resource_collection
                - @api.transformer.helper

        api.transformer.helper:
            class: Eliberty\ApiBundle\Helper\TransformerHelper
            arguments:
                - @api.ressource.transformer_resolver

        api.iri_converter:
            class: Dunglas\ApiBundle\Api\IriConverter
            arguments:
                - @api.resource_collection
                - @api.data_provider
                - @api.router
                - @property_accessor

        webhook.doctrine.entity_listener_resolver:
            class: Eliberty\ApiBundle\WebHook\Doctrine\Listener\EntityListenerResolver
            arguments:
                - @service_container

        webhook.listener:
            class : Eliberty\ApiBundle\WebHook\Listener\WebHookListener
            arguments:
                - @doctrine.orm.default_entity_manager
                - @logger
            tags:
                - { name: kernel.event_subscriber }

        nelmio_api_doc.extractor.api_doc_extractor:
            class: Eliberty\ApiBundle\Nelmio\Extractor\ApiDocExtractor
            arguments:
                - @service_container
                - @router
                - @annotation_reader
                - @nelmio_api_doc.doc_comment_extractor
                - []
                - @api.transformer.helper
                - @api.json_ld.normalizer.item
                - @api.resource_collection
                - @form.registry
