parameters:
#    eliberty_api.example.class: Eliberty\ApiBundle\Example

services:
#    eliberty_api.example:
#        class: %eliberty_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
