parameters:
    eliberty_api.normalizer.item.class: 'Eliberty\ApiBundle\JsonLd\Serializer\Normalizer'
    eliberty_api.doctrine.orm.data_provider.class: 'Eliberty\ApiBundle\Doctrine\Orm\DataProvider'

imports:
    - { resource: filter.yml }
    - { resource: webhook.yml }

services:
    api.resource:
        class: 'Eliberty\ApiBundle\Api\Resource'
        abstract: true

    api.json_ld.entrypoint_builder:
        class: 'Eliberty\ApiBundle\JsonLd\EntrypointBuilder'
        arguments:
             - '@api.resource_collection'
             - '@api.iri_converter'
             - '@api.router'

    api.doctrine.orm.data_provider:
        class: '%eliberty_api.doctrine.orm.data_provider.class%'
        arguments:
             - '@doctrine'
             - '%api.collection.order%'
             - '%api.collection.pagination.page_parameter_name%'
             - '%api.collection.pagination.items_per_page.number%'
             - '%api.collection.pagination.items_per_page.enable_client_request%'
             - '%api.collection.pagination.items_per_page.parameter_name%'

    api.doctrine.orm.default_data_provider:
        parent : 'api.doctrine.orm.data_provider'
        tags:
             - { name: api.data_provider }

    eliberty.api.serializer:
        class: 'Eliberty\ApiBundle\Api\ApiSerializer'

    eliberty.api.hydra.normalizer.violation.list.error:
        class: 'Eliberty\ApiBundle\Hydra\Serializer\ErrorViolationListNormalizer'
        arguments:
             - '@api.router'
             - '%kernel.debug%'
             - '@property_accessor'
        lazy: true
        tags:
             - { name: api.serializer.normalizer }

    api.hydra.normalizer.error:
        class: 'Eliberty\ApiBundle\Hydra\Serializer\ErrorNormalizer'
        arguments:
             - '@api.router'
             - '@translator'
             - '%kernel.debug%'
        tags:
             - { name: api.serializer.normalizer }

    api.jsonld.normalizer.error:
        class: 'Eliberty\ApiBundle\JsonLd\Serializer\ErrorNormalizer'
        arguments:
             - '@translator'
             - '%kernel.debug%'
        tags:
             - { name: api.serializer.normalizer }

    api.xml.normalizer.error:
        class: 'Eliberty\ApiBundle\Xml\Serializer\ErrorNormalizer'
        arguments:
             - '@translator'
             - '%kernel.debug%'
        tags:
             - { name: api.serializer.normalizer }

    api.normalizer.item:
        class: '%eliberty_api.normalizer.item.class%'
        arguments:
            - '@api.transformer.helper'
            - '@logger'
        tags:
            - { name: serializer.normalizer }

    api.ressource.transformer_resolver:
        class: 'Eliberty\ApiBundle\Transformer\Listener\TransformerResolver'
        arguments:
            - '@request_stack'

    api.handler.resolver:
        class: 'Eliberty\ApiBundle\Handler\HandlerResolver'

    api.form.resolver:
        class: 'Eliberty\ApiBundle\Form\FormResolver'

    api.resource_collection:
        class: 'Eliberty\ApiBundle\Api\ResourceCollection'
        lazy: true

    api.operation_factory:
        class: 'Eliberty\ApiBundle\Api\Operation\OperationFactory'
        arguments:
            - '@api.transformer.helper'

    api.router:
        class: 'Eliberty\ApiBundle\Routing\Router'
        arguments:
            - '@router'
            - '@api.resource_collection'
            - '@property_accessor'

    api.transformer.helper:
        class: 'Eliberty\ApiBundle\Helper\TransformerHelper'
        arguments:
            - '@api.ressource.transformer_resolver'

    api.documentation.helper:
        class: 'Eliberty\ApiBundle\Helper\DocumentationHelper'
        arguments:
            - '@eliberty.api.controller_name_parser'
            - '@annotation_reader'
            - '@api.transformer.helper'
            - '@service_container'

    api.route_loader:
        class: 'Eliberty\ApiBundle\Routing\ApiLoader'
        public: 'false'
        arguments:
            - '@api.resource_collection'
            - '@kernel'
        tags:
            - { name: routing.loader }

    eliberty.api.controller_name_parser:
        class: 'Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser'
        arguments:
            - '@kernel'

    api.hydra.documentation_builder:
        class: 'Eliberty\ApiBundle\Hydra\ApiDocumentationBuilder'
        arguments:
            - '@api.resource_collection'
            - '@api.json_ld.context_builder'
            - '@router'
            - '%api.title%'
            - '%api.description%'
            - '@api.documentation.helper'

    api.json_ld.context_builder:
        class: 'Eliberty\ApiBundle\JsonLd\ContextBuilder'
        arguments:
            - '@api.router'
            - '@event_dispatcher'
            - '@api.resource_collection'
            - '@api.mapping.class_metadata_factory'
            - '@api.documentation.helper'

    api.helper.apply.criteria:
        class: 'Eliberty\ApiBundle\Helper\ApplyCriteriaEmbed'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@api.resource_collection'
            - '@api.data_provider'

    api.init.filter.embed:
        class: 'Eliberty\ApiBundle\Helper\InitFilterEmbed'
        arguments:
            - '@router'
            - '@api.resource_collection'
            - '@doctrine'
            - '@property_accessor'

    api.hydra.listener.request_exception:
        class: 'Eliberty\ApiBundle\Api\EventListener\RequestExceptionListener'
        arguments:
            - '@request_stack'
            - '@eliberty.api.serializer'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    api.group.context.loader:
      class: 'Eliberty\ApiBundle\Context\GroupsContextLoader'
      arguments:
          - '%kernel.bundles%'
          - '@generic_cache'

    api.group.context.chainer:
      class: 'Eliberty\ApiBundle\Context\GroupsContextChainer'
      arguments:
          - '@api.group.context.loader'

    parent.handler.api.v2:
        class: Eliberty\ApiBundle\Handler\BaseHandler
        arguments:
            - '@instance.form.contact.api.v2'
            - '@router'
            - '@doctrine.orm.entity_manager'
            - '@api.resource_collection'
            - '@event_dispatcher'