parameters:
    eliberty_api.normalizer.item.class: Eliberty\ApiBundle\JsonLd\Serializer\Normalizer
    eliberty_api.doctrine.orm.data_provider.class: Eliberty\ApiBundle\Doctrine\Orm\DataProvider

imports:
    - { resource: filter.yml }
    - { resource: webhook.yml }

services:
    api.resource:
        class: Eliberty\ApiBundle\Api\Resource
        abstract: true

    api.json_ld.entrypoint_builder:
        class: Eliberty\ApiBundle\JsonLd\EntrypointBuilder
        arguments:
             - @api.resource_collection
             - @api.iri_converter
             - @api.router

    api.doctrine.orm.data_provider:
        class: %eliberty_api.doctrine.orm.data_provider.class%
        arguments:
             - @doctrine
             - %api.collection.order%
             - %api.collection.pagination.page_parameter_name%
             - %api.collection.pagination.items_per_page.number%
             - %api.collection.pagination.items_per_page.enable_client_request%
             - %api.collection.pagination.items_per_page.parameter_name%

    api.doctrine.orm.default_data_provider:
        parent : api.doctrine.orm.data_provider
        tags:
             - { name: api.data_provider }

    eliberty.api.hydra.normalizer.violation.list.error:
        class: Eliberty\ApiBundle\Hydra\Serializer\ErrorViolationListNormalizer
        arguments:
             - @api.router
             - %kernel.debug%
             - @property_accessor
        tags:
             - { name: serializer.normalizer }

    api.json_ld.normalizer.item:
        class: %eliberty_api.normalizer.item.class%
        arguments:
            - @api.resource_collection
            - @api.data_provider
            - @api.router
            - @api.mapping.class_metadata_factory
            - @api.json_ld.context_builder
            - @property_accessor
            - @api.transformer.helper
            - @request_stack
            - @doctrine.orm.entity_manager
            - @logger
        tags:
            - { name: serializer.normalizer }

    api.ressource.transformer_resolver:
        class: Eliberty\ApiBundle\Transformer\Listener\TransformerResolver
        arguments:
            - @request_stack

    api.resource_collection:
        class: Eliberty\ApiBundle\Api\ResourceCollection
        arguments:
            - @request_stack
        lazy: true

    api.operation_factory:
        class: Eliberty\ApiBundle\Api\Operation\OperationFactory
        arguments:
            - @api.transformer.helper

    api.router:
        class: Eliberty\ApiBundle\Routing\Router
        arguments:
            - @router
            - @api.resource_collection
            - @property_accessor

    api.transformer.helper:
        class: Eliberty\ApiBundle\Helper\TransformerHelper
        arguments:
            - @api.ressource.transformer_resolver

    api.documentation.helper:
        class: Eliberty\ApiBundle\Helper\DocumentationHelper
        arguments:
            - @eliberty.api.controller_name_parser
            - @annotation_reader
            - @api.transformer.helper
            - @service_container

    api.route_loader:
        class: Eliberty\ApiBundle\Routing\ApiLoader
        public: false
        arguments:
            - @api.resource_collection
            - @kernel
        tags:
            - { name: routing.loader }

    eliberty.api.controller_name_parser:
        class: Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser
        arguments:
            - @kernel

    api.hydra.documentation_builder:
        class: Eliberty\ApiBundle\Hydra\ApiDocumentationBuilder
        arguments:
            - @api.resource_collection
            - @api.json_ld.context_builder
            - @router
            - %api.title%
            - %api.description%
            - @api.documentation.helper

    api.json_ld.context_builder:
        class: Eliberty\ApiBundle\JsonLd\ContextBuilder
        arguments:
            - @api.router
            - @event_dispatcher
            - @api.resource_collection
            - @api.mapping.class_metadata_factory
            - @api.documentation.helper



