services:
    api.webhook.entity_listener:
        class: Eliberty\ApiBundle\WebHook\Doctrine\Listener\WebHookBaseListener
        arguments:
            - @event_dispatcher
            - @logger
        tags:
            - { name: doctrine.entity_listener }

    webhook.doctrine.entity_listener_resolver:
        class: Eliberty\ApiBundle\WebHook\Doctrine\Listener\EntityListenerResolver

    webhook.listener:
        class : Eliberty\ApiBundle\WebHook\Listener\WebHookListener
        arguments:
            - @doctrine.orm.default_entity_manager
            - @api.router
            - @api.mapping.class_metadata_factory
            - @api.json_ld.context_builder
            - @api.resource_collection
            - @request_stack
            - @logger
        tags:
            - { name: kernel.event_subscriber }
